version: "3.9"
services:
  app:
    build: .
    environment:
      - FILES_DIR=/data/files
      - DB_HOST=database
    ports:
      - 4000:4000
    volumes:
      - ./prod_data/files:/data/files
    depends_on:
      - database
    restart: unless-stopped
  database:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./prod_data/db:/data/db
